# Site settings
title: Fanny & Florian Hochzeit
url: 
description: "Hochzeitsseite für die Hochzeit von Fanny und Florian"
skills: "28.08.2021"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
 title: Danke
 text: Wir freuen uns auf einen schönen gemeinsamen Tag!

# Build settings
markdown: kramdown
permalink: pretty

#for faqs
faqs:
  - title: What is this?
    body: <p>a collapsible div</p>

  - title: Does it have any dependencies?  
    body: <p>Nope</p>

  - title: Is it complicated?
    body: <p>Well, not really, but you do have to follow a few rules. It works best if you use jekyll and a data file to loop thru and build the proper strucure.</p>  

  - title: Do I have to use it with Jekyll?
    body: <p>Nope, it just makes it easier to have the correct toggle/body index numbers.</p>

  - title: You made it so it is perfect and works under all use cases right?
    body: <p>Well, no. It works great as a simple expandable FAQ, but I have not tried to use it for anything else. For example, if you stick a large image in one of the bodies it may not work properly.</p>
