# Site settings
title: Fanny & Florian Hochzeit
url: 
description: "Hochzeitsseite für die Hochzeit von Fanny und Florian"
skills: "28.08.2021"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
 title: Danke
 text: Wir freuen uns auf einen schönen gemeinsamen Tag!

# Build settings
markdown: kramdown
permalink: pretty

#for faqs
faqs:
  title: What is this?
  body: <p>a collapsible div</p>