# Site settings
title: 10 Jahre - Zeit für Feiern!
url: 
description: "Florian und Fanny Hochzeit"
skills: "28.08.2021"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 328F4E 
  primary-rgb: "50,143,78" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Build settings
markdown: kramdown
permalink: pretty

#for faqs
faqs:
  - title: Was macht ihr wegen COVID-19?
    body: Eine Hoffnung ist natürlich, das die Situation, wie letztes Jahr, im August etwas entspannter ist. Ob die Hochzeit stattfindet hängt natürlich von der gesetzlichen Lage ab. Wir planen aktuell Antigen Tests für alle bei Eintritt zu organisieren um die Sicherheit aller Gäste zu Gewährleisten. Falls die Hochzeit nicht stattfindet oder um ein Jahr verschoben wird werden wir euch selbstverständlich so früh wie möglich kontaktieren.
  
  - title: Gibt es eine Kleiderordnung?
    body: Nein, kommt am besten in bequemer Kleidung. Bunt ist gut. No pressure though. Bei (dem von uns bestelltem) Schönwetter findet ein großteil der Hochzeit im freien statt und verlagert sich dann erst für das Essen nach drinnen.
  
  - title: Muss ich beim Picknick am Boden sitzen?
    body: Für alle die nicht wollen gibt es auch Heurigenbänke
  
  - title: Was machen wir bei Schlechtwetter?
    body: Bei Schlechtwetter wird sich ein großteil der Aktivität in die Labstelle verlagern.
  
  - title: Kann ich meinen Hund mitnehmen?
    body: Nein, im Lainzer Tiergarten sind Hunde nicht erlaubt.
